name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating Issue!'
        pr-message: 'Thank you for creating pull request'
 
  test-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ['web', 'api', 'ui']
    permissions:
      issues: write
      pull-requests: write
    needs: greeting  
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Running ${{ matrix.name }} tests'
        
